### ISSUE TITLE
How to set static port for devbox in windows

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2devbox-web#108]
![screenshot 2017-05-13 22 20 57](https://cloud.githubusercontent.com/assets/1908873/26026711/a19862d6-382a-11e7-9127-eea06cb455b3.png)
I'am using devbox for my local windows. Everything works ok only this port problem. This happens when i restart container and port changed so i can't access anymore! Is there a way to set this port static? I have changed port in docker-compose but it not apply when install

**Comment by astragt** [comment]
http://devdocs.magento.com/guides/v2.0/install-gde/docker/docker-ref.html#devbox-static-port
I had the same question: https://github.com/magento/magento2devbox-web/issues/92
