### ISSUE TITLE
How Can i install Magento DevBox on Ubuntu 16.04

### ISSUE THREAD

**Issue by sandeep1082** [magento/magento2devbox-web#110]

**Comment by yaroslavGoncharuk** [comment]
@sandeep1082 Thanks for reporting this issue.

To use the Magento DevBox, you must have a system with the following:
64-bit Windows 10 Pro, Enterprise and Education (1511 November update, Build 10586 or later)
Mac OS 10.10.3 “Yosemite” or later

Linux support is in our backlog
You can vote here #18
