### ISSUE TITLE
Windows download copy link includes ./ which doesn't work

### ISSUE THREAD

**Issue by xcomSteveJohnson** [magento/magento2devbox-web#14]
When you're done downloading the `.zip` file on Windows, the field that shows you the command to run starts with `./`, which works on UNIX but not Windows.

Remove `./` and it will work.

```
./m2devbox-init.bat
'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by yaroslavGoncharuk** [comment]
@xcomSteveJohnson thank you for your report, we created internal ticket MAGETWO-63433

**Comment by yaroslavGoncharuk** [comment]
fixed
