### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by snez** [magento/magento2devbox-web#16]
Hi all,

Thanks for taking the time to put this docker container together. A bit of initial feedback on the project:

- [x] There is no documentation on how to set this up on either Github, or most importantly on  https://hub.docker.com/r/magento/magento2devbox-web/
- [x] Docker compose is not utilized, which means that things are very complicated with inexperienced docker users. With docker compose, MySQL, Nginx, PHPFPM, Redis, Varnish can all be put together and started in a single docker-compose up command and shut down with a docker-compose down. You can even have development or production configuration files, for example:
```
docker-compose -f docker-compose.yml -f development-docker-compose.yml up -d --build
```
would spin up a development environment whereas

    docker-compose -f docker-compose.yml -f production-docker-compose.yml up -d --build

would spin up a production ready environment.

- [x] There are no tags on Docker Hub that would make it easy for developers to choose or upgrade versions of Magento, upgrading dependencies and depreciating PHP versions along the way. The tag system used by other official images is great, for example see https://hub.docker.com/_/php/ for a comprehensive list of all available php versions.

Thanks again

**Comment by fooman** [comment]
> Docker composer is not utilized

Can you check your contents of the script m2devbox-init.sh - in mine I have 

```
docker-compose up --build -d
```

From my understanding the DevBox is, as the name implies, only meant to quick start development at this stage.

**Comment by vrann** [comment]
@snez 
1. Documentation is here http://devdocs.magento.com/guides/v2.1/install-gde/docker/docker-over.html
2. current repository contains just the web container. However DevBox download page (https://magento.com/tech-resources/download) will provide an archive with the docker-compose.yml file and couple of scripts to install and run Magento. Docker Compose combines web, db, varnish and other containers
3. The DevBox is not bound to particular Magento version, Magento is installed on top of it. The version of Magento to install is configured in environment variables in the docker-compose.yml file. It is possible to select a version on the download page as well. In future we are going to support multiple php versions, that's where suggestion to use tags will be very usefull.

Thansk!

**Comment by snez** [comment]
Thanks for the info and the documentation update @fooman and @vrann, all good.
