### ISSUE TITLE
Could not open input file: bin/magento -   [Exception] Command failed to execute

### ISSUE THREAD

**Issue by andreasacca** [magento/magento2devbox-web#27]
Hello,
I have troubles while executing the shell command:

Digest: sha256:9eeaffc43e1e46e8ae17b5fc770281a90d388d879ef78d02525d8d6c2c83a197
Status: Downloaded newer image for mysql:5.6
Creating magento2devbox_db_4b38cb68478a2c0f0d30d690d46c6656
Creating magento2devbox_web_4b38cb68478a2c0f0d30d690d46c6656
Install Magento

[IN PROGRESS] Sync Started.

.
[IN PROGRESS] Unison sync started

Executing shell command:
cd /var/www/magento2 && php bin/magento setup:install --base-url=http://127.0.0.1:32769/ --db-host=db --db-name=magento2 --db-user=root --db-password=root --admin-firstname=Magento --admin-lastname=User --admin-email=user@example.com --admin-user=admin --admin-password=admin123 --language=en_US --currency=USD --timezone=America/Chicago --use-rewrites=1 --backend-frontname=admin
Could not open input file: bin/magento

<img width="1167" alt="screen shot 2017-01-19 at 23 06 37" src="https://cloud.githubusercontent.com/assets/1486077/22129100/f6cc5df4-de9b-11e6-897f-4f664b658ba1.png">

**Comment by DerekMarcinyshyn** [comment]
Looks like you need to go into the docker "web" vm via the docker-composer exec command
http://devdocs.magento.com/guides/v2.1/install-gde/docker/docker-commands.html

`docker-compose exec --user=magento2 web /bin/bash`

then change directory to where your magento2 is installed.

For me:
`cd magento2` and you should be able to `php bin/magento list`

**Comment by johnhughes1984** [comment]
I also had this issue, running `m2devbox-init.sh` again solved it for me (I was using EE version), but appreciate not a long term fix!

**Comment by andreasacca** [comment]
Solved. The magento2 path was wrong in my .ylm file, I changed and relaunched the script and it worked. Thank you
