### ISSUE TITLE
Remove vim dependency

### ISSUE THREAD

**Issue by ashsmith** [magento/magento2devbox-web#33]
Vim shouldn't be included in the image as most people will not need to modify the contents of the container, and they can just install vim if they need to.

It'll help cut down on the size of the image, and I don't believe many people will need it.

Happy to work on this PR.

**Comment by vrann** [comment]
@ashsmith the intended audience of the DevBox are developers who debug their applications. Vim is just too useful not to be present in the container. I found myself installing it every time and I see same with other developers. Besides, it's not a production environment where such tools are not needed or can be harmful.

As long as there are no functional concerns with this, I'd close the issue.

**Comment by ashsmith** [comment]
Ok, agreed, lets close this 👍
