### ISSUE TITLE
Speed up unison checks

### ISSUE THREAD

**Issue by ashsmith** [magento/magento2devbox-web#38]
In `check-unison.sh` the loop will sleep for 10 seconds. This is a long time to wait for file changes to be picked up.

Was there a particular reason for 10 seconds?

I'd propose dropping it as low as possible (1-2 seconds?)

**Comment by vrann** [comment]
@ashsmith check-unison.sh is a script which ensures that Unison is running in "--repeate watch" mode. In this mode unison is running as a daemon and watches for the changes in the filesystem on both sides. It updates files as soon as it get notification from the filesystem that file is updated (instantly) 

Having that, "sleep 10 sec"  means that every 10 seconds check-unison.sh script will check that Unison is still running in the background. It will restart the Unison process if it's not running.
