### ISSUE TITLE
Problem with installation - ./m2devbox-init.sh

### ISSUE THREAD

**Issue by Hector68** [magento/magento2devbox-web#41]
Windows 10 home basic
Docker version 1.12.1, build 23cf638

Build docker images
Creating network "build8446ddec7cb334eb3856695ca33e98cc_default" with the default driver
Creating magento2devbox_db_8446ddec7cb334eb3856695ca33e98cc
Creating magento2devbox_web_8446ddec7cb334eb3856695ca33e98cc
Install Magento
[31mERROR[0m: Interactive mode is not yet supported on Windows.
Please pass the -d flag when using `docker-compose exec`.

(./shared/webroot: No such file or directory)
or to its parent ./shared
(./shared: No such file or directory)
Try 'timeout --help' for more information.
Contacting server...
Fatal error: Cannot find canonical name of ./shared/webroot: unable to cd either to it

**Comment by piotrekkaminski** [comment]
@Hector68 Windows 10 Home Basic is not compatible with Docker:

Docker for Windows requires 64bit Windows 10 Pro, Enterprise and Education (1511 November update, Build 10586 or later) and Microsoft Hyper-V. 

https://docs.docker.com/docker-for-windows/
