### ISSUE TITLE
After restarting web container, Admin loads without images (404 in title bar)

### ISSUE THREAD

**Issue by xcomSteveJohnson** [magento/magento2devbox-web#42]
Windows

1.  Installed DevBox, Admin worked.
2.  Restarted web container while testing a documentation procedure.
3.  Tried Admin on its new port but got 404 ("Whoops") page with no CSS or images

**Expected**: Should be able to access the Admin on a new port
**Actual**: Cannot connect, get 404 and no images

`docker-compose ps` result after restarting web container with `docker-compose restart web`

The new port is 32793

```
docker-compose ps
                       Name                                     Command              State                                             Ports
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
magento2devbox_db_18c4e4d3c5a541f37e9cffd35f1bf74e    docker-entrypoint.sh mysqld    Up      0.0.0.0:32788->3306/tcp
magento2devbox_web_18c4e4d3c5a541f37e9cffd35f1bf74e   /usr/local/bin/entrypoint.sh   Up      0.0.0.0:32794->22/tcp, 44100/tcp, 0.0.0.0:32792->5000/tcp, 0.0.0.0:32793->80/tcp, 9000/tcp
```

**Comment by KTamas** [comment]
exact same issue here, OSX latest, it drives me crazy

**Comment by yaroslavGoncharuk** [comment]
@xcomSteveJohnson thank you for your report, we created internal ticket MAGETWO-63652

**Comment by yaroslavGoncharuk** [comment]
fixed
