### ISSUE TITLE
Ports for WEB changes after each docker-compose restart

### ISSUE THREAD

**Issue by madonzy** [magento/magento2devbox-web#52]
The path **web/unsecure/base_url** in **core_config_table** (table in Magento) contain address with port from installation _http://127.0.0.1:32769/_, but when I restart Docker using **docker-compose restart** then ports are changed, but record in DB stay the same. The problem is that all static files fail to load with that old port.

**Comment by xcomSteveJohnson** [comment]
Did you try running `m2devbox-reset` instead?

**Comment by madonzy** [comment]
@xcomSteveJohnson no, should I try?

**Comment by piotrekkaminski** [comment]
@madonzy yes - this is how it works. To allow running multiple instances and avoid port conflicts, we let docker assign ports. And there is m2devbox-reset script that updates Magento with the new port. Please let us know if it worked for you.

**Comment by madonzy** [comment]
@piotrekkaminski yes, this solves the problem, thanks ;)
