### ISSUE TITLE
Could not find package magento/project-enterprise-edition with version 2.1.3.  

### ISSUE THREAD

**Issue by gdoug-guidance** [magento/magento2devbox-web#59]
During a brand new build, I get this error:
                                                                                 
  [InvalidArgumentException]                                                     
  Could not find package magento/project-enterprise-edition with version 2.1.3.

**Comment by xcomSteveJohnson** [comment]
Check your auth keys. While I haven't tried it, I believe this is the error you get if you try to download EE using CE keys.

**Comment by gdoug-guidance** [comment]
I see that the docs say that... http://devdocs.magento.com/guides/v2.1/install-gde/prereq/integrator_install_ee.html

But I set up a new set of keys, just in case. Same error, so I have keys for the marketplace, and for connect... and neither of them work.

What is the difference between CE keys and EE keys? Do EE keys get generated in a different way than the docs say to create keys?

**Comment by xcomSteveJohnson** [comment]
Yes. When you purchase EE, Support enables access to EE for your keys. It happens behind the scenes. There is no difference in the way the user generates keys.

I think you have to use the same keys to install Magento and get/update extensions from Marketplace.

**Comment by gdoug-guidance** [comment]
Just an update, I had to contact EE support and have them open my account to download M2 EE. Thanks for the help.
