### ISSUE TITLE
Data not share  in phpstorm

### ISSUE THREAD

**Issue by mrtuvn** [magento/magento2devbox-web#64]
my Docker-compose http://pastebin.com/raw/KM0B9vAS
![docker-phpstorm](https://cloud.githubusercontent.com/assets/1908873/22588177/3c331986-ea37-11e6-8027-3fe178d1f203.png)
shared directory owned by root so i can't modify
Using ubuntu 16.10 with docker 1.13.0

**Comment by yaroslavGoncharuk** [comment]
@mrtuvn Thanks for reporting this issue.

To use the Magento DevBox, you must have a system with the following:
64-bit Windows 10 Pro, Enterprise and Education (1511 November update, Build 10586 or later)
Mac OS 10.10.3 “Yosemite” or later
