### ISSUE TITLE
Windows 10 + Docker + WMware Workstation

### ISSUE THREAD

**Issue by samuelecarpene** [magento/magento2devbox-web#65]
I currently use WMware Workstation to virtualize some virtual machines.
Docker use Hyper-V that is incompatible with WMware Workstation.
Is there any solution to run docker and vmware at the same time?

**Comment by yaroslavGoncharuk** [comment]
@samuelecarpene Thanks for reporting this issue.

Unfortunately, you cannot work with Docker, VirtualBox, Vagrant or VMware simultaneously on Windows 10.

See please https://docs.docker.com/docker-for-windows/faqs/
