### ISSUE TITLE
Cannot create network when starting container - solved

### ISSUE THREAD

**Issue by piotrekkaminski** [magento/magento2devbox-web#68]
[see below for update - too many networks, remove some, VPN possibly has nothing to do with it]

@xcomSteveJohnson can you add it to the FAQ section?

When you are on VPN, when trying to install devbox you can run into the following issues: ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network

More info: https://github.com/docker/libnetwork/issues/779

**Comment by kingletas** [comment]
Can you try restarting the docker service with the --bip option?

**Comment by xcomSteveJohnson** [comment]
Published: http://devdocs.magento.com/guides/v2.0/install-gde/docker/docker-trouble.html#Problem-You-want-to-start-over-

**Comment by piotrekkaminski** [comment]
Actually the problem is different @xcomSteveJohnson . Found it finally. Docker has limit of 32 networks total and each time you run a container it creates a new network. Sometimes they don't get cleaned. In my case, "docker network ls" shown 32 networks and i had to delete some (or all) using "docker network rm $(docker network ls -q)" - now it works.

**Comment by xcomSteveJohnson** [comment]
Thanks, updated the topic
