### ISSUE TITLE
Core integration test suite fails on fresh devbox.

### ISSUE THREAD

**Issue by Vinai** [magento/magento2devbox-web#74]
I didn't look why, but when I start a fresh devbox instance, wait for it to be ready, and run the integration tests (from within the box on the command line), a large number are skipped or fail.  
It would be very valuable to have the devbox as a baseline to run the integration test suite.

**Comment by victorgugo** [comment]
Hi @Vinai . Could you please provide the command you use to run integration tests?
If you use PHPStorm - you can copy this command from it's specific toolbar.

Thank's in advance.

**Comment by yaroslavGoncharuk** [comment]
@Vinai thank you for your report, we created internal ticket MAGETWO-64758

**Comment by yaroslavGoncharuk** [comment]
fixed
