### ISSUE TITLE
Error 503 Backend fetch failed

### ISSUE THREAD

**Issue by ivagarfitt** [magento/magento2devbox-web#77]
Hi 

I am trying to find `/etc/default/varnish`or similar to be able to fix this error.
Not sure where in DevBox container to find it.

Thank you

**Comment by victorgugo** [comment]
Hi @ivagarfitt 

Thank you for reporting the issue. This file is located in varnish container.
You can login to varnish container by one of the following commands:
```
docker-compose exec varnish bash # in case you are in the same dir where m2devbox-init script is
docker exec -it <varnish_container_full_name> bash # from any place in your host
```

Could you please, specify steps you done before getting this error. This will help identify and fix the problem.

Thank you.

**Comment by ivagarfitt** [comment]
Thanks for this.

I was developing admin module. It was giving me error that Controller class is not defined. So i done it, went back and 503 showed up. I have devbox with Varnish, Redis full page and session. I change all this to '0' and restart it and problem was gone.

**Comment by edwint88** [comment]
I have the same issue, but what is all this? that you've changed to 0 (@ivagarfitt)

**Comment by ivagarfitt** [comment]
@edwint88 I am not using this anymore so cannot help you much. But only place where this can be set to '0' is some config file that comes with devbox.

**Comment by edwint88** [comment]
@ivagarfitt Thanks for posting, for me did the trick to change the configuration of the varnish and some restarts of the web container (see more here: https://community.magento.com/t5/Programming-Questions/how-to-fix-Error-503-Backend-fetch-failed/m-p/84061#M3461)
