### ISSUE TITLE
Adding a custom PHP file results in File Not Found

### ISSUE THREAD

**Issue by Jrb1x** [magento/magento2devbox-web#84]
I've added a php file in my pub folder and added it to my locations in `nginx.conf`:

`location ~ (index|get|static|report|404|503|test)\.php$`

but `http://127.0.0.1:32781/test.php` results in a "File not found" page.

**Comment by yaroslavGoncharuk** [comment]
@Jrb1x  thanks for reporting this issue.

In addition, identify, please:
- Your OS type and version 
- Docker version and additional settings
- Magento Edition and Version
- Project Source (New Installation or Use Existing Local Installation)

**Comment by Jrb1x** [comment]
@yaroslavGoncharuk 

Mac OS 10.12.1
Docker version 17.03.0-ce
Magento Enterprise 2.1.0
New installation

**Comment by Jrb1x** [comment]
I believe this may be the same issue at #79, I'll leave it up to you to close this issue as a duplicate or not.

**Comment by yaroslavGoncharuk** [comment]
Yes. You right.
Issue #79 is in progress now and will be fixed ASAP.

Thank You.
