### ISSUE TITLE
php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by alankrit29** [magento/magento2devbox-web#90]
Hello Team,

I am trying  to install Magento DevBox on my system having specifications as follows:

OS: MacOS (OS X EI Capitan version 10.11.6)
RAM: 6 GB
MAGENTO VERSION: 2.1.5
MAGENTO EDITION: Community Edition
PROJECT SOURCE: New Installation

When I run command ./m2devbox-init.sh, I get the following errors:

![issue1](https://cloud.githubusercontent.com/assets/26565388/24156419/77c4be28-0e7c-11e7-8e1c-1684e7e0b632.png)

Also status of docker containers are:

![issue2](https://cloud.githubusercontent.com/assets/26565388/24156475/a2017d5c-0e7c-11e7-98fd-b971527162ef.png)

**Comment by dannydnz** [comment]
Looks like the database container isn't running for some reason. Notice the STATUS "exited (141)". 

Without any more information a guess would be that you possible don't have enough memory in your docker vm (docker for mac).

If this is not the case whats the output of for database container logs?

````sh
docker-compose logs db
````

**Comment by alankrit29** [comment]
Hello, 

Output of docker-compose logs db is attached below:
![test5](https://cloud.githubusercontent.com/assets/26565388/24352047/a98a0c64-1305-11e7-974b-f358bc9ec463.png)

**Comment by alankrit29** [comment]
Hello Team,

Any help on this issue would be appreciated.

**Comment by alankrit29** [comment]
Hello Team,

Is there anyone attending this issue?

**Comment by YanivRan** [comment]
Having the same issue here, did you manage to solve it?

**Comment by rlavooij** [comment]
Same issue here, 
fresh install of devbox on a fresh docker install on macos 10.12 (its the only containers in docker)

**Comment by sv3tli0** [comment]
Same problem with 100% clean new Docker ..
What I found is that the VOLUME into the DB setting is making the problem (some InnoDB shits) comming at this DB setting at docker-composer.yml
   - "./shared/db:/var/lib/mysql"

My problem comes from a file inside ./shared/db/ > **ibdata1** ..
I found solution by removing the file and starting 2 times the init bash file .. At the second time it created a new not empty file and everything worked as charm ..
