### ISSUE TITLE
How to use static ports for SSH/DB/Web?

### ISSUE THREAD

**Issue by astragt** [magento/magento2devbox-web#92]
Hi,

can someone explain how to use static ports for the devbox, so i dont have to change the ports in PHPStorm everytime i restart my computer?

The documentation actually mention it here: http://devdocs.magento.com/guides/v2.1/install-gde/docker/docker-ref.html 

> To set static listen ports so you don’t have to reconfigure PhpStorm every time you start DevBox, see Set static ports.

And "Set static ports" is a link but... it just puts you onto the same page without any information

**Comment by o-iegorov** [comment]
You need to modify your docker-compose.yml before running ma2devbox-init script:

- find "ports" section: 

> ports:
>           - "80"
>           - "22"

- modify with wanted values (ensure that selected ports are free)
> ports:
>           - "1748:80"
>           - "2222:22"

In this example you will get 127.0.0.1:1748 as you http port and 127.0.0.1:2222 as your ssh port

**Comment by astragt** [comment]
Thanks that worked out.
Would be nice if someone with the permissions would add it to the , kinda useless link, in the documentary.

**Comment by xcomSteveJohnson** [comment]
@astragt Sorry about this oversight. I'll update the documentation after I verify it works.
