### ISSUE TITLE
Host files config for multi store using devbox

### ISSUE THREAD

**Issue by RobbThompson** [magento/magento2devbox-web#95]
Has anyone any experience in the best practise for mapping local host names for multiple store fronts? 

I am using devbox on windows, with only the web & db containers.  I am looking to run a multi-store development and staging environment. 

Ideally instead of going to 127.0.0.1 which takes me to the default install, I want web-a.local and web-b.local to be associated with the corresponding Magento store via htaccess as I would normally. 

At the moment I am unclear as to  where I am looking to modify the hosts file, is it on the client or on the devbox? If it is via the devbox i assume I am looking to use the docker --add-hosts command to map.

If anyone can help me give my head a wobble and point me in the correct direction I would appreciate it.

**Comment by xcomSteveJohnson** [comment]
I want to be clear this is speculation because I've never tried it. Seeing as the web server runs on Docker and forwards requests to a port available on Windows, I would first try setting the `hosts` on Docker. I think it would be super easy to try it. If it doesn't work, then try it on Windows.
