### ISSUE TITLE
Mac OSX auth.json  failed to open stream: Permission denied  

### ISSUE THREAD

**Issue by user3748173** [magento/magento2devbox-web#97]
When trying to install devbox in Mac OS X I get.

```
[RuntimeException]                                                                               
  Could not read /home/magento2/.composer/auth.json                                                
  file_get_contents(/home/magento2/.composer/auth.json): failed to open stream: Permission denied  

```
I downloaded Magento 2 CE (Community Edition).
**What i have done:**
I have created new magento keys, downloaded new docker directory and tried with them.

I have installed the devbox successfully before. I Just can not understand what might be the problem now? Also I am new at docker so where the directory "/home/magento2/..." is located?
 
I have narrowed it down that composer does not have enough permissions in directory. 
**My question is, when devbox installs Magento 2 what permissions it needs?** - I installed composer to my local machine and ran the command getting same error. When I added `sudo` to the command all went OK.

**Comment by xcomSteveJohnson** [comment]
To answer your question about the root folder, see http://devdocs.magento.com/guides/v2.1/install-gde/docker/docker-ref.html#devbox-root-dir.

**Comment by user3748173** [comment]
The link you provided, does not contain any information about directory permissions _(Why to use sudo in front of Terminal command?)_.

**Comment by utiuam** [comment]
Try changing the permission auth.json to 775, it work for me
